"""Abstract planning agent using a shared planning template.

This module defines a reusable planning workflow for all planning-based AI
employees.
"""

import logging
from abc import ABC, abstractmethod

from app.engine.core.base_agent import BaseAgent
from app.engine.core.task import Plan
from app.engine.parser import ResponseParser
from app.services.planning_service import PlanningService


logger = logging.getLogger(__name__)


class PlanningAgent(BaseAgent, ABC):
    """Base class for planning-oriented agents.

    Subclasses provide only ``agent_name`` while this class owns the complete
    plan-generation algorithm.
    """

    def __init__(self, planning_service: PlanningService, response_parser: ResponseParser) -> None:
        """Initialize planning dependencies.

        Args:
            planning_service: Service used to generate agent-specific responses.
            response_parser: Parser used to convert JSON response text to ``Plan``.
        """
        super().__init__(self.agent_name)
        self.__planning_service: PlanningService = planning_service
        self.__response_parser: ResponseParser = response_parser

    @property
    @abstractmethod
    def agent_name(self) -> str:
        """Return the stable agent name used for prompt resolution."""

    @property
    def planning_service(self) -> PlanningService:
        """Return planning service for subclass extension points.

        Returns:
            The injected ``PlanningService`` instance.
        """
        return self.__planning_service

    @property
    def response_parser(self) -> ResponseParser:
        """Return response parser for subclass extension points.

        Returns:
            The injected ``ResponseParser`` instance.
        """
        return self.__response_parser

    def before_plan(self) -> None:
        """Hook executed before plan generation.

        Subclasses may override to perform pre-processing.
        """
        pass

    def after_plan(self, plan: Plan) -> None:
        """Hook executed after successful plan parsing.

        Args:
            plan: Parsed plan generated by the planning workflow.
        """
        pass

    def plan(self, goal: str) -> Plan:
        """Generate and parse a plan using the shared template algorithm.

        Args:
            goal: User goal to be planned.

        Returns:
            Parsed ``Plan`` returned by the response parser.

        Raises:
            ValueError: If ``goal`` is empty or whitespace-only.
            Exception: Re-raises downstream workflow failures unchanged.
        """
        normalized_goal = goal.strip() if isinstance(goal, str) else ""
        if not normalized_goal:
            raise ValueError("goal must be a non-empty, non-whitespace string")

        logger.info(
            "planning_agent_started",
            extra={"event": "planning_agent_started", "agent_name": self.agent_name},
        )

        try:
            self.before_plan()
            response = self.planning_service.generate_plan(
                agent_name=self.agent_name,
                goal=normalized_goal,
            )
            plan = self.response_parser.parse_plan(response)
            self.after_plan(plan)
        except Exception as exc:
            logger.exception(
                "planning_agent_failed",
                extra={
                    "event": "planning_agent_failed",
                    "agent_name": self.agent_name,
                    "error_type": type(exc).__name__,
                },
            )
            raise

        logger.info(
            "planning_agent_completed",
            extra={"event": "planning_agent_completed", "agent_name": self.agent_name},
        )
        return plan
